name: kong_api
version: 0.1.1
description: >
  Simple library to use kong
  Kong : https://getkong.org
author: ProfileRH, PLATEL Kevin <platel.kevin@gmail.com>
homepage: https://github.com/ProfileRH/amqp_rpc_binder
environment:
  sdk: ">=1.15.0 <2.0.0"
dependencies:
  rpc: ">=0.5.6 <0.6.0"
  http: "^0.11.3+3"
